# Generated by Django 5.0.6 on 2024-07-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color_code', models.CharField(max_length=7)),
                ('collection_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
