# Generated by Django 5.0.6 on 2024-07-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_colorcollection_delete_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorsRalClassic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgcolor', models.CharField(blank=True, max_length=20, null=True)),
                ('ral_code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('cmyk_coated', models.CharField(blank=True, max_length=50, null=True)),
                ('cmyk_uncoated', models.CharField(blank=True, max_length=50, null=True)),
                ('html_hex', models.CharField(blank=True, max_length=7, null=True)),
                ('rgb', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColorsRalDesignEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgcolor', models.CharField(blank=True, max_length=20, null=True)),
                ('ral_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('cymk', models.CharField(blank=True, max_length=50, null=True)),
                ('rgb_percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('hex_code', models.CharField(blank=True, max_length=7, null=True)),
                ('rgb_values', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Сolors_ncs_pantone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgcolor', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=100)),
                ('value1', models.CharField(blank=True, max_length=50, null=True)),
                ('value2', models.CharField(blank=True, max_length=50, null=True)),
                ('value3', models.CharField(blank=True, max_length=50, null=True)),
                ('value4', models.CharField(blank=True, max_length=50, null=True)),
                ('hex_code', models.CharField(blank=True, max_length=7, null=True)),
                ('r', models.IntegerField(blank=True, null=True)),
                ('g', models.IntegerField(blank=True, null=True)),
                ('b', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ColorCollection',
        ),
    ]
