# Generated by Django 5.0.6 on 2024-07-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_colorsralclassic_colorsraldesigneffect_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorsPantone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgcolor', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=100)),
                ('value1', models.CharField(blank=True, max_length=50, null=True)),
                ('value2', models.CharField(blank=True, max_length=50, null=True)),
                ('value3', models.CharField(blank=True, max_length=50, null=True)),
                ('value4', models.CharField(blank=True, max_length=50, null=True)),
                ('hex_code', models.CharField(blank=True, max_length=7, null=True)),
                ('r', models.IntegerField(blank=True, null=True)),
                ('g', models.IntegerField(blank=True, null=True)),
                ('b', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColorsRalEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgcolor', models.CharField(blank=True, max_length=20, null=True)),
                ('ral_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('cymk', models.CharField(blank=True, max_length=50, null=True)),
                ('rgb_percentage', models.CharField(blank=True, max_length=50, null=True)),
                ('hex_code', models.CharField(blank=True, max_length=7, null=True)),
                ('rgb_values', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Сolors_ncs_pantone',
            new_name='ColorsNcs',
        ),
        migrations.RenameModel(
            old_name='ColorsRalDesignEffect',
            new_name='ColorsRalDesign',
        ),
    ]
